In [27]:
import numpy as np

Use the following code for the questions below:

In [28]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

1. How many negative numbers are there?

In [29]:
# Create a mask to filter the negatives
neg_mask = (a<0)

# Apply mask and subsequently a len() function to the filtered array
len(a[neg_mask])

4

2. How many positive numbers are there?

In [30]:
# Just like above, make a mask to filter positives
pos_mask = (a>0)

# Apply mask and add len() function
len(a[pos_mask])

5

3. How many even positive numbers are there?

In [31]:
# Make a pos_even mask that is both positive and even numbers
pos_even = pos_mask & (a%2==0)

# Apply mask
len(a[pos_even])

3

4. If you were to add 3 to each data point, how many positive numbers would there be?

In [32]:
# First add 3 to each data point
added_3 = a+3

# Was going to add pos_mask to the filter BUT
# pos_mask was based off the old values not the new ones so it's not gonna work well

# For current simplicity, just gonna do it in-house
len(added_3[added_3>0])

10

5. If you squared each number, what would the new mean and standard deviation be?

In [33]:
# Make the new squared array
squared_a = a**2
squared_a

array([ 16, 100, 144, 529,   4,   1,   0,   0,   0,  36,   9,  49])

In [34]:
# Display the mean
squared_a.mean()

74.0

In [35]:
# Display the standard deviation
squared_a.std()

144.0243035046516

6. A common statistical operation on a dataset is **centering**. This means to adjust the data such that the mean of the data is 0. This is done by subtracting the mean from each data point. Center the data set. See [this link](https://www.theanalysisfactor.com/centering-and-standardizing-predictors/) for more on centering

In [36]:
centered_squared = squared_a - squared_a.mean()
centered_squared

array([-58.,  26.,  70., 455., -70., -73., -74., -74., -74., -38., -65.,
       -25.])

7. Calculate the z-score for each data point. Recall that the z-score is given by: Z = (x−μ)/σ

In [37]:
zscore = sum(a)/squared_a.std()
zscore

0.249957813535528

8. Copy the setup and exercise directions from [More Numpy Practice](https://gist.github.com/ryanorsinger/c4cf5a64ec33c014ff2e56951bc8a42d) into your nump_exercises.py and add your solutions.

# Life w/o numpy to life with numpy
## Setup 1

In [38]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

## Use python's built in functionality/operators to determine the following:
### Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list

In [39]:
sum_of_a = sum(a)
print('Sum of a:',sum_of_a)

Sum of a: 55


### Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list

In [40]:
min_of_a = min(a)
print('Min of a:',min_of_a)

Min of a: 1


### Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list

In [41]:
max_of_a = max(a)
print('Max of a:',max_of_a)

Max of a: 10


### Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list

In [42]:
mean_of_a = sum(a)/len(a)
print('Mean of a:',mean_of_a)

Mean of a: 5.5


### Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together

In [43]:
product_of_a = 1
for i in a:
    # print(product_of_a,i)
    product_of_a *= i

print('Product of a:',product_of_a)

Product of a: 3628800


### Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]

In [44]:
squares_of_a = [i**2 for i in a]

print('Squares of a:',squares_of_a)

Squares of a: [1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


### Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers

In [45]:
odds_in_a = [i for i in a if i%2!=0]

print('Odds in a:',odds_in_a)

Odds in a: [1, 3, 5, 7, 9]


### Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.

In [46]:
evens_in_a = [i for i in a if i%2==0]

print('Evens in a:',evens_in_a)

Evens in a: [2, 4, 6, 8, 10]


## What about life in two dimensions? A list of lists is matrix, a table, a spreadsheet, a chessboard...
## Setup 2: Consider what it would take to find the sum, min, max, average, sum, product, and list of squares for this list of two lists.

In [47]:
b = [
    [3, 4, 5],
    [6, 7, 8]
]

### Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. **Hint, you'll first need to make sure that the "b" variable is a numpy array**
<code>sum_of_b = 0
for row in b:
    sum_of_b += sum(row)</code>

In [54]:
b = np.array(b)

sum_of_b = np.sum(b)

sum_of_b

33

### Exercise 2 - refactor the following to use numpy. 
<code>min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1])</code>

In [57]:
min_of_b = np.min(b)

min_of_b

3

### Exercise 3 - refactor the following maximum calculation to find the answer with numpy.
<code> max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])</code>

In [58]:
max_of_b = np.max(b)

max_of_b

8

### Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.
<code>product_of_b = 1
for row in b:
    for number in row:
        product_of_b *= number</code>

In [59]:
product_of_b = np.product(b)

product_of_b

20160

### Exercise 6 - refactor the following to use numpy to find the list of squares 
<code>squares_of_b = []
for row in b:
    for number in row:
        squares_of_b.append(number**2)</code>

In [60]:
squares_of_b = b**2

squares_of_b

array([[ 9, 16, 25],
       [36, 49, 64]])

### Exercise 7 - refactor using numpy to determine the odds_in_b
<code>odds_in_b = []
for row in b:
    for number in row:
        if(number % 2 != 0):
            odds_in_b.append(number)</code>

In [62]:
odds_in_b = b[b%2!=0]

odds_in_b

array([3, 5, 7])

### Exercise 8 - refactor the following to use numpy to filter only the even numbers
<code>evens_in_b = []
for row in b:
    for number in row:
        if(number % 2 == 0):
            evens_in_b.append(number)</code>

In [63]:
evens_in_b = b[b%2==0]

evens_in_b

array([4, 6, 8])

### Exercise 9 - print out the shape of the array b.

In [66]:
b.shape

(2, 3)

### Exercise 10 - transpose the array b.

In [81]:
b.transpose()

array([[3, 6],
       [4, 7],
       [5, 8]])

### Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)

In [79]:
b.flatten()

array([3, 4, 5, 6, 7, 8])

### Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)

In [78]:
b.reshape((6,1))

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

## Setup 3

In [89]:
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

# HINT, you'll first need to make sure that the "c" variable is a numpy array prior to using numpy array methods.
c = np.array(c)

### Exercise 1 - Find the min, max, sum, and product of c.

In [90]:
np.min(c)

1

In [91]:
np.max(c)

9

In [92]:
np.prod(c)

362880

### Exercise 2 - Determine the standard deviation of c.

In [93]:
np.std(c)

2.581988897471611

### Exercise 3 - Determine the variance of c.

In [94]:
np.var(c)

6.666666666666667

### Exercise 4 - Print out the shape of the array c

In [95]:
c.shape

(3, 3)

### Exercise 5 - Transpose c and print out transposed result.

In [97]:
c.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

### Exercise 6 - Get the dot product of the array c with c. 

In [103]:
np.dot(c,c)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

### Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261

In [102]:
sum_c_transposed = np.sum(c * c.transpose())
sum_c_transposed

261

### Exercise 8 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.

In [104]:
prod_c_transposed = np.prod(c * c.transpose())
prod_c_transposed

131681894400

## Setup 4

In [105]:
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]
d = np.array(d)

### Exercise 1 - Find the sine of all the numbers in d

In [106]:
np.sin(d)

array([[ 0.89399666, -0.98803162,  0.85090352,  0.        ,  0.58061118,
        -0.80115264],
       [ 0.85090352, -0.89399666,  0.98803162, -0.17604595,  0.89399666,
         0.        ],
       [-0.30481062,  0.85090352, -0.85090352,  0.89399666, -0.85090352,
        -0.80115264]])

### Exercise 2 - Find the cosine of all the numbers in d

In [107]:
np.cos(d)

array([[-0.44807362,  0.15425145,  0.52532199,  1.        ,  0.81418097,
        -0.59846007],
       [ 0.52532199, -0.44807362,  0.15425145,  0.98438195, -0.44807362,
         1.        ],
       [-0.95241298,  0.52532199,  0.52532199, -0.44807362,  0.52532199,
        -0.59846007]])

### Exercise 3 - Find the tangent of all the numbers in d

In [108]:
np.tan(d)

array([[-1.99520041, -6.4053312 ,  1.61977519,  0.        ,  0.71312301,
         1.33869021],
       [ 1.61977519,  1.99520041,  6.4053312 , -0.17883906, -1.99520041,
         0.        ],
       [ 0.32004039,  1.61977519, -1.61977519, -1.99520041, -1.61977519,
         1.33869021]])

### Exercise 4 - Find all the negative numbers in d

In [109]:
np.negative(d)

array([[ -90,  -30,  -45,    0, -120, -180],
       [ -45,   90,   30, -270,  -90,    0],
       [ -60,  -45,   45,  -90,   45, -180]])

### Exercise 5 - Find all the positive numbers in d

In [110]:
np.positive(d)

array([[ 90,  30,  45,   0, 120, 180],
       [ 45, -90, -30, 270,  90,   0],
       [ 60,  45, -45,  90, -45, 180]])

### Exercise 6 - Return an array of only the unique numbers in d.

In [111]:
np.unique(d)

array([-90, -45, -30,   0,  30,  45,  60,  90, 120, 180, 270])

### Exercise 7 - Determine how many unique numbers there are in d.

In [112]:
len(np.unique(d))

11

### Exercise 8 - Print out the shape of d.

In [113]:
d.shape

(3, 6)

### Exercise 9 - Transpose and then print out the shape of d.

In [115]:
d.transpose().shape

(6, 3)

### Exercise 10 - Reshape d into an array of 9 x 2

In [116]:
d.reshape(9,2)

array([[ 90,  30],
       [ 45,   0],
       [120, 180],
       [ 45, -90],
       [-30, 270],
       [ 90,   0],
       [ 60,  45],
       [-45,  90],
       [-45, 180]])